### ISSUE TITLE
Weather icons missing and causing errors

### ISSUE THREAD

**Issue by luedi0** [pjimenezmateo/kindle-wallpaper#15]
When updating the screensaver picture during the day and night, missing icons cause errors and halting the script.
I assume, there need to be more icons with the *n suffix.

**Comment by pjimenezmateo** [comment]
That may be true, I thought I got all the codes from https://openweathermap.org/weather-conditions if you could check the codes and tell me which one is missing that would be great. If not I will check once I have the time.

**Comment by pjimenezmateo** [comment]
I have merged your 2 PR, again thank you very much! Do you have the codes of the missing weather icons? So I can try to look into it.

**Comment by luedi0** [comment]
Pleasure, I haven't compared the possible codes to the existing icons. I do however think that a lot of night time icons are missing. If you only update in the morning, there is rarely a night time weather symbol necessary. I set the cronjob to update every 3 hours though.

**Comment by luedi0** [comment]
So far no more errors.
