### ISSUE TITLE
Error in 802n.svg

### ISSUE THREAD

**Issue by StephanAAU** [pjimenezmateo/kindle-wallpaper#20]
Does not render correctly. Replace file with this to fix.

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
<path fill="none" d="M91.9,85.7c-0.8,0-1.5,0.1-2.2,0.4l-1.1,0.4l-0.2-1.2c-0.6-3.9-3.9-6.8-7.9-6.8c-4.5,0-8.1,3.6-8.1,8.1,c0-0.1,0.1,0,0.1,0.3l0,1.1l-1.1-0.1c-0.2,0-0.3,0-0.3,0c-2.1,0-3.9,1.7-3.9,3.8c0,0,0,0,0,0c0,0,0,0,0,0.1c0,0,0,0,0,0.1v1.3,		L66,92.8c-0.3-0.1-0.6-0.2-0.9-0.2c-1.8,0-3.2,1.4-3.2,3.2c0,0.9,0.3,1.3,0.8,1.7c0.5,0.4,1.4,0.6,2.4,0.6h13.1h7.1h6.6,		c3.4,0,6.2-2.8,6.2-6.2C98.1,88.5,95.3,85.7,91.9,85.7z"/><path d="M21.2,52c1.7,5.6,5.2,10.4,10,13.7C26.6,62.2,23.1,57.5,21.2,52z"/><path d="M91.9,83.8c-0.7,0-1.3,0.2-1.9,0.3c-1.1-4.3-4.9-7.5-9.5-7.5c-5.3,0-9.6,4.2-9.9,9.4c-2.6,0.2-4.6,2.2-5.1,4.7,		c-0.2,0-0.3-0.1-0.4-0.1c-2.8,0-5.1,2.3-5.1,5.1c0,1.4,0.7,2.6,1.7,3.2c1,0.7,2.2,0.9,3.5,0.9h13.1h7.1h6.6c4.5,0,8.1-3.6,8.1-8.1,		S96.4,83.8,91.9,83.8z M91.9,98.1h-6.6h-7.1H65.1c-1,0-1.9-0.2-2.4-0.6c-0.5-0.3-0.8-0.8-0.8-1.7c0-1.8,1.4-3.2,3.2-3.2,		c0.3,0,0.6,0.1,0.9,0.2l1.2,0.4v-1.3c0-0.1,0-0.1,0-0.1c0-0.1,0,0,0-0.1c0,0,0,0,0,0c0-2.1,1.8-3.8,3.9-3.8c0,0,0.1,0,0.3,0,l1.1,0.1l0-1.1c0-0.3-0.1-0.3-0.1-0.3c0-4.5,3.6-8.1,8.1-8.1c4,0,7.3,3,7.9,6.8l0.2,1.2l1.1-0.4c0.7-0.3,1.4-0.4,2.2-0.4,c3.4,0,6.2,2.8,6.2,6.2C98.1,95.3,95.3,98.1,91.9,98.1z"/><path d="M73.6,55c-4,2.2-8.5,3.4-13.3,3.4C44.6,58.6,31.8,46,31.7,30.3c0-4.4,0.9-8.6,2.7-12.3c-8.9,4.8-14.8,14.3-14.8,25.1,		c0,3.1,0.6,6.1,1.5,8.9c1.9,5.5,5.4,10.3,10,13.7c4.8,3.5,10.6,5.6,17,5.5C59.4,71.1,69.1,64.5,73.6,55z"/>
</svg>
`

**Comment by pjimenezmateo** [comment]
Thanks! Your code was not rendering properly (I am not sure why) but I was able to fix the svg by reducing the paths.

it should be fixed now, let me know if anything else does not work :)
