### ISSUE TITLE
yahoo weather change in weather API

### ISSUE THREAD

**Issue by papypaprika** [pjimenezmateo/kindle-wallpaper#5]
Hi All,
Love this implementation, but Yahoo changed the way to connect to their weather API and the server script doesn't work anymore. Anybody skilled enough to adjust to openweathermap or forecast.io ?

**Comment by luedi0** [comment]
Hi,
Ran into the same problem.
Yahoo has phased out support for unauthorised API calls.
You will need to request credentials to query the new URL
https://weather-ydn-yql.media.yahoo.com/forecastrss...

See also:
https://developer.yahoo.com/weather/
https://community.openhab.org/t/solved-yahoo-weather-does-not-work-anymore/62583

Now figuring out how to query with oath API keys...

**Comment by pjimenezmateo** [comment]
Hi, sorry for the long delay in answering. Currently I do not have enough time to update this project, and I am unsure if this works with newer versions of Kindle, I have since moved to a paperwhite.

However, if somebody wants to tackle this I will assist as much as I can :D

**Comment by luedi0** [comment]
Hi Pablo,
Thanks for getting back to us.
I only have little Python experience but think adapting the Yahoo sample code to the weather parser should be quick. (Already have credentials etc.)
https://developer.yahoo.com/weather/documentation.html#oauth-python

**Comment by luedi0** [comment]
This is an updated parse_weather.py to work with the new yahoo query model (obfuscated credentials ;) )
It seems to work so far but I am still fixing the parse_ical.py 

import time, uuid, urllib, urllib2
from xml.dom import minidom
import datetime
import hmac, hashlib
import codecs
from base64 import b64encode


#Weather API Python sample code
#Copyright 2019 Oath Inc. Licensed under the terms of the zLib license see https://opensource.org/licenses/Zlib for terms.

#Basic info (You need your own credentials from https://developer.yahoo.com/weather/)
url = 'https://weather-ydn-yql.media.yahoo.com/forecastrss'
method = 'GET'
app_id = 'llu87gik6'
consumer_key = 'wp49e8ghrsubdnvbgi7ky6kyv6i76fi76fel5usirtbdjfvelgusbdfkx'
consumer_secret = '23o845gweurbilsvdgwo7485gilueso8isue5'
concat = '&'
query = {'location': 'bad homburg,de', 'format': 'xml', 'u': 'c'}
oauth = {
    'oauth_consumer_key': consumer_key,
    'oauth_nonce': uuid.uuid4().hex,
    'oauth_signature_method': 'HMAC-SHA1',
    'oauth_timestamp': str(int(time.time())),
    'oauth_version': '1.0'
}

#Prepare signature string (merge all params and SORT them)
merged_params = query.copy()
merged_params.update(oauth)
sorted_params = [k + '=' + urllib.quote(merged_params[k], safe='') for k in sorted(merged_params.keys())]
signature_base_str =  method + concat + urllib.quote(url, safe='') + concat + urllib.quote(concat.join(sorted_params), safe='')

#Generate signature
composite_key = urllib.quote(consumer_secret, safe='') + concat
oauth_signature = b64encode(hmac.new(composite_key, signature_base_str, hashlib.sha1).digest())

#Prepare Authorization header
oauth['oauth_signature'] = oauth_signature
auth_header = 'OAuth ' + ', '.join(['{}="{}"'.format(k,v) for k,v in oauth.iteritems()])

#Send request
url = url + '?' + urllib.urlencode(query)
request = urllib2.Request(url)
request.add_header('Authorization', auth_header)
request.add_header('X-Yahoo-App-Id', app_id)
weather_xml = urllib2.urlopen(request).read()
print(weather_xml)

#Feeding yahoo data into DOM
dom = minidom.parseString(weather_xml)

#Get weather Tags
xml_temperatures = dom.getElementsByTagName('yweather:forecast')

#Get today Tag
today = xml_temperatures[0]

#Get info
low = today.getAttribute('low')
high = today.getAttribute('high')
image = today.getAttribute('code')
date = today.getAttribute('date')
image_url = 'icons/' + image + '.svg'

#Open SVG to process
output = codecs.open('icons/template.svg', 'r', encoding='utf-8').read()


#Read icon (Just the path line)
f = codecs.open(image_url ,'r', encoding='utf-8')
f.readline()
icon = f.readline()
f.close()

#Insert icons and temperatures
output = output.replace('TODAY',date)
output = output.replace('ICON_ONE',icon)
output = output.replace('HIGH_ONE',high)
output = output.replace('LOW_ONE',low)

#Write output
codecs.open('after-weather.svg', 'w', encoding='utf-8').write(output)

**Comment by pjimenezmateo** [comment]
Oh wow, great! Do you want to do a pull request to this repo so I can approve it and you appear as a contributor? Or do you want me to merge the code myself and list you on the README?

I will also add the steps to get a custom key.

**Comment by luedi0** [comment]
I will send a pull request and we go from there. Thank you.

**Comment by pjimenezmateo** [comment]
I am currently porting the code to the openweather API. It should be done in a couple of hours (the only thing left is changing the weather codes). I will merge your code but I will most likely overwrite with mine later, since it is shorter and I prefer that.

But I am merging it so you are a contributor :D

**Comment by pjimenezmateo** [comment]
The OpenWeather migration is complete, I also added new icons. I hope you enjoy it! :D
