### ISSUE TITLE
server python script prerequisites

### ISSUE THREAD

**Issue by luedi0** [pjimenezmateo/kindle-wallpaper#9]
Hey,
Since I've been using the deprecated python 2.7 until now, I noticed errors using url lib.request and others.
Maybe the readme should include prerequisites like python3 and python3-requests etc.

Errors below...

Traceback (most recent call last):
  File "programs/parse_weather.py", line 1, in <module>
    import urllib.request, json
ImportError: No module named request
Traceback (most recent call last):
  File "programs/parse_ical.py", line 11, in <module>
    urllib.urlretrieve (ICAL_URL, "basic.ics")
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 248, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return self.open_unknown(fullurl, data)
  File "/usr/lib/python2.7/urllib.py", line 225, in open_unknown
    raise IOError, ('url error', 'unknown url type', type)
IOError: [Errno url error] unknown url type: 'webcal'

**Comment by pjimenezmateo** [comment]
You are absolutely right, the new version is for Python3 since 2 is deprecated. Are you able to use Python3? I will add the requirements soon.

**Comment by luedi0** [comment]
That's great. I just made python 3 the priority with update-alternatives command.
A good explanation for Debian is here [https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux](url)

**Comment by pjimenezmateo** [comment]
Amazing! Is the ical working fine? Or should I take a look?

**Comment by luedi0** [comment]
I will need to see whether my ical URL (exported from iCloud) is correct or whether I will need to test it with a google calendar ical URL.
So far, it isn't working yet.

**Comment by luedi0** [comment]
I'm using the standard google calendar private ical URL.
Now getting this error:
`  File "programs/parse_ical.py", line 27
    if( date_start.timetuple().tm_yday == datetime.datetime. now().timetuple().tm_yday ):
                                                                                                                                                  ^
TabError: inconsistent use of tabs and spaces in indentation `
...
The pointer is at the ":"
Does that mean that we need to replace all tabs with 4 spaces?

**Comment by pjimenezmateo** [comment]
Let me quickly fix that.

**Comment by pjimenezmateo** [comment]
Try now.

**Comment by luedi0** [comment]
Thanks, I will on Sunday.
Have a nice weekend!

**Comment by pjimenezmateo** [comment]
I have updated and tested all the python programs. Now they work with Python3. If anything is broken open another issue :D
